version: "3.8"

services:
  mongo:
        container_name: professional_db
        image: mongo:6.0
        ports:
          - 27017:27017
        volumes:
          - taskdb:/data/db
        environment:
          - MONGO_INITDB_ROOT_USERNAME=admin
          - MONGO_INITDB_ROOT_PASSWORD=admin

volumes:
    taskdb: